# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d1924cc4a6052778d980c2e1ec69b3e796a2791a3061eb35ba8ea021ccea85e0484f38e4c1554f8caf319ec91357e93ac5a83d1ddf9bced3b8be97375d2951

test:
  secret_key_base: de2ca2ea47db644279f95d2382f31c8fc00da461805cfcbacf88e625e5928de04a10a6b6bc3636d727bb9ed7ba0863f1e01b3c33c082d395e68734f133f4bc4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
